### ISSUE TITLE
Error with weewx V4.1 under Python3

### ISSUE THREAD

**Issue by Mkamaro** [glennmckechnie/weewx-sqlbackup#2]
Hello,
i have installed the new stable version 4.1 in parallel to test if my hardware and the extensions work with python3.
When I run sqlbackup I got this Error.
`File "/home/weewx/weewx_v4/bin/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/home/weewx/weewx_v4/bin/weewx/reportengine.py", line 280, in start
    self.run()
  File "/home/weewx/weewx_v4/bin/weewx/cheetahgenerator.py", line 147, in run
    self.initExtensions(gen_dict[section_name])
  File "/home/weewx/weewx_v4/bin/weewx/cheetahgenerator.py", line 191, in initExtensions
    self.search_list_objs.append(class_(self))
  File "/home/weewx/weewx_v4/bin/user/sqlbackup.py", line 545, in __init__
    f.write(hed_output)
TypeError: write() argument must be str, not bytes
`
After that I got a file with 0 bytes for the dump of the schema and no file for the dump of the database.
Does sqlbackup support weewx v4.1 and Python3? What can I do to solve the error?
Thank you for help
Best regards
MKamaro

**Comment by glennmckechnie** [comment]
I've gone through and converted line 545 and a few more areas to cope with the byte / str issue.
These don't catch me out but perhaps that's because our locale files are different?

Try the new file ... sqlbackup.py 

I've tested those changes here and all is still okay but your testing will be the conclusive one.
If there are further issues then let me know and I'll work on them ASAP.

I'm still running 4.0.0b18 I haven't shifted to 4.1 yet but that shouldn't be an issue.

**Comment by Mkamaro** [comment]
Thanks for the quick feedback and for adapting the code.

I did a "quick" test and now I get the following error message:
`Traceback (most recent call last):
  File "/home/weewx/weewx_v4/bin/weewx/reportengine.py", line 197, in run
    obj.start()
  File "/home/weewx/weewx_v4/bin/weewx/reportengine.py", line 280, in start
    self.run()
  File "/home/weewx/weewx_v4/bin/weewx/cheetahgenerator.py", line 147, in run
    self.initExtensions(gen_dict[section_name])
  File "/home/weewx/weewx_v4/bin/weewx/cheetahgenerator.py", line 191, in initExtensions
    self.search_list_objs.append(class_(self))
  File "/home/weewx/weewx_v4/bin/user/sqlbackup.py", line 595, in __init__
    f.write(dump_output)
  File "/usr/lib/python3.5/gzip.py", line 258, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
`

Are there such major differences in the Python versions or in the output of SQlite?
My installation is on "Raspbian-Stretch" with:
`>python3 ---version`
`Python 3.5.3`

`>apt list sqlite3`
`Auflistung... Fertig`
`sqlite3/oldstable,now 3.16.2-5+deb9u1 armhf  [installiert]`

Many thanks for your work
MKamaro

**Comment by glennmckechnie** [comment]
You are on the money with it being python specific. 
I'm running python 3.7 and it appears that it handles the error differently, it wouldn't show up; ran it under python 3.5 and sure enough it popped up.

Besides that fix, I've done some further tweaking to bring it into full sync with weewx4, changed some logging details and ran it through pylint as it was all getting a bit ugly. 
Hopefully I haven't broken anything else in the process but it's been working with sqlite3 and mysql all afternoon.
Also it's been running with weewx v4.1.0

You know the drill :-)

Thanks for the initial heads up, and also for pursuing it. 
Without feedback like yours, things stay broken.

cheers
Glenn

**Comment by Mkamaro** [comment]
Many thanks for your effort,
I have tested the new code and there were no error messages or problems, and the recovery of the backup (created with your addition) was successful.
Thanks again

Many greetings
MKamaro

*** With your consent I will close the issue ***
